# Generated by Django 5.2.6 on 2025-10-04 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='cname',
        ),
    ]
