# Generated by Django 5.2.6 on 2025-10-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('car_type', models.CharField(help_text='e.g. SUV, Sedan, Hatchback', max_length=50)),
                ('price_per_day', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='cars/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
