# Generated by Django 5.2.6 on 2025-10-09 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_car'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='contact',
            new_name='contact_number',
        ),
        migrations.AlterField(
            model_name='booking',
            name='car_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.car'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_location',
            field=models.CharField(max_length=200),
        ),
    ]
